{
 "title": "Kafka",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Global Partition Count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TopicCount",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_globaltopiccount",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MessagesInPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_server_brokertopicmetrics_messagesin_total{topic!~\"__.*\",topic!=\"\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{topic}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BytesInPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(kafka_server_brokertopicmetrics_bytesin_total[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BytesOutPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(kafka_server_brokertopicmetrics_bytesout_total[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RequestQueueTimeMs ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_requestmetrics_requestqueuetimems{quantile=~\"0.9[5|8|99]?\", request=\"Produce\"}) by (instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Produce - {{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(kafka_network_requestmetrics_requestqueuetimems{quantile=~\"0.9[5|8|99]?\", request=\"FetchConsumer\"}) by (instance)",
     "legendFormat": "FetchConsumer - {{instance}}"
    },
    {
     "expr": "sum(kafka_network_requestmetrics_requestqueuetimems{quantile=~\"0.9[5|8|99]?\", request=\"FetchFollower\"}) by (instance)",
     "legendFormat": "FetchFollower - {{instance}}"
    }
   ]
  },
  {
   "title": "ResponseQueueTimeMs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_requestmetrics_responsequeuetimems{quantile=~\"0.9[5|8|99]?\", request=\"Produce\"}) by (instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Produce - {{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(kafka_network_requestmetrics_responsequeuetimems{quantile=~\"0.9[5|8|99]?\", request=\"FetchFollower\"}) by (instance)",
     "legendFormat": "FetchFollower -- {{instance}}"
    },
    {
     "expr": "sum(kafka_network_requestmetrics_responsequeuetimems{quantile=~\"0.9[5|8|99]?\", request=\"FetchConsumer\"}) by (instance)",
     "legendFormat": "FetchConsumer - {{instance}}"
    }
   ]
  },
  {
   "title": "LocalTimeMs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_requestmetrics_localtimems{quantile=~\"0.9[5|8|99]?\", request=\"FetchFollower\"}) by (instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "FetchFollower - {{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(kafka_network_requestmetrics_localtimems{quantile=~\"0.9[5|8|99]?\", request=\"FetchConsumer\"}) by (instance)",
     "legendFormat": "FetchConsumer - {{instance}}"
    },
    {
     "expr": "sum(kafka_network_requestmetrics_localtimems{quantile=~\"0.9[5|8|99]?\", request=\"Produce\"}) by (instance)",
     "legendFormat": "Produce - {{instance}}"
    }
   ]
  },
  {
   "title": "RemoteTimeMs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_requestmetrics_remotetimems{quantile=~\"0.9[5|8|99]?\", request=\"Produce\"}) by (instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Produce - {{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(kafka_network_requestmetrics_remotetimems{quantile=~\"0.9[5|8|99]?\", request=\"FetchConsumer\"}) by (instance)",
     "legendFormat": "FetchConsumer - {{instance}}"
    },
    {
     "expr": "sum(kafka_network_requestmetrics_remotetimems{quantile=~\"0.9[5|8|99]?\", request=\"FetchFollower\"}) by (instance)",
     "legendFormat": "FetchFollower - {{instance}}"
    }
   ]
  },
  {
   "title": "NetworkProcessorAvgIdlePercent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "kafka_network_socketserver_networkprocessoravgidlepercent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ControlPlaneProcessorAvgIdlePercent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "kafka_network_socketserver_controlplanenetworkprocessoravgidlepercent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RequestHandlerAvgIdlePercent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LeaderElectionRateAndTimeMs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_controller_controllerstats_leaderelectionrateandtimems{quantile=~\"0.9[5|8|99]?\"}) by (instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Controller State",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_controllerstate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ControllerChangeRateAndTimeMs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (kafka_controller_controllerstats_controllerchangerateandtimems{quantile=~\"0.9[5|8|99]?\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TopicDeletionRateAndTimeMs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (kafka_controller_controllerstats_topicdeletionrateandtimems{quantile=~\"0.9[5|8|99]?\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PartitionReassignmentRateAndTimeMs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (kafka_controller_controllerstats_partitionreassignmentrateandtimems{quantile=~\"0.9[5|8|99]?\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}