{
 "title": "Kafka System Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk usage Brokers (Percent)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{job=\"kafka\"})-sum(node_filesystem_free_bytes{job=\"kafka\"}))/(sum(node_filesystem_size_bytes{job=\"kafka\"}))"
    }
   ]
  },
  {
   "title": "System Load  (cpu)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "node_load5{instance=\"ec2-34-244-87-88.eu-west-1.compute.amazonaws.com:9101\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "node_load5{instance=\"ec2-34-253-193-58.eu-west-1.compute.amazonaws.com:9101\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "node_load5{instance=\"ec2-52-215-235-67.eu-west-1.compute.amazonaws.com:9101\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Mapped Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Mapped_bytes{job=\"kafka\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Bytes Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{job=\"kafka\", device=\"eth0\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Bytes Transmited",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{job=\"kafka\", device=\"eth0\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "File Descriptors Usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(node_filefd_maximum{instance=\"ec2-34-244-87-88.eu-west-1.compute.amazonaws.com:9101\"}-node_filefd_allocated{instance=\"ec2-34-244-87-88.eu-west-1.compute.amazonaws.com:9101\"})/node_filefd_maximum{instance=\"ec2-34-244-87-88.eu-west-1.compute.amazonaws.com:9101\"}",
     "legendFormat": "broker0"
    },
    {
     "expr": "(node_filefd_maximum{instance=\"ec2-34-253-193-58.eu-west-1.compute.amazonaws.com:9101\"}-node_filefd_allocated{instance=\"ec2-34-253-193-58.eu-west-1.compute.amazonaws.com:9101\"})/node_filefd_maximum{instance=\"ec2-34-253-193-58.eu-west-1.compute.amazonaws.com:9101\"}",
     "legendFormat": "broker1"
    },
    {
     "expr": "(node_filefd_maximum{instance=\"ec2-52-215-235-67.eu-west-1.compute.amazonaws.com:9101\"}-node_filefd_allocated{instance=\"ec2-52-215-235-67.eu-west-1.compute.amazonaws.com:9101\"})/node_filefd_maximum{instance=\"ec2-52-215-235-67.eu-west-1.compute.amazonaws.com:9101\"}",
     "legendFormat": "broker2"
    }
   ]
  },
  {
   "title": "Disk usage Broker0 (Percent)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{instance=\"ec2-34-244-87-88.eu-west-1.compute.amazonaws.com:9101\"})-sum(node_filesystem_free_bytes{instance=\"ec2-34-244-87-88.eu-west-1.compute.amazonaws.com:9101\"}))/(sum(node_filesystem_size_bytes{instance=\"ec2-34-244-87-88.eu-west-1.compute.amazonaws.com:9101\"}))",
     "legendFormat": "broker0"
    },
    {
     "expr": "(sum(node_filesystem_size_bytes{instance=\"ec2-34-253-193-58.eu-west-1.compute.amazonaws.com:9101\"})-sum(node_filesystem_free_bytes{instance=\"ec2-34-253-193-58.eu-west-1.compute.amazonaws.com:9101\"}))/(sum(node_filesystem_size_bytes{instance=\"ec2-34-253-193-58.eu-west-1.compute.amazonaws.com:9101\"}))",
     "legendFormat": "broker1"
    },
    {
     "expr": "(sum(node_filesystem_size_bytes{instance=\"ec2-52-215-235-67.eu-west-1.compute.amazonaws.com:9101\"})-sum(node_filesystem_free_bytes{instance=\"ec2-52-215-235-67.eu-west-1.compute.amazonaws.com:9101\"}))/(sum(node_filesystem_size_bytes{instance=\"ec2-52-215-235-67.eu-west-1.compute.amazonaws.com:9101\"}))",
     "legendFormat": "broker2"
    }
   ]
  }
 ]
}