{
 "title": "Zookeeper",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "ZookeeperNative", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AvgRequestLatency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    { "expr": "zookeeper_avgrequestlatency" }
   ]
  },
  {
   "title": "MaxRequestLatency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    { "expr": "zookeeper_maxrequestlatency" }
   ]
  },
  {
   "title": "OutstandingRequests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    { "expr": "zookeeper_outstandingrequests" }
   ]
  },
  {
   "title": "NumAliveConnections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "zookeeper_numaliveconnections" }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used{instance=\"zookeeper:8080\"}"
    },
    {
     "expr": "java_lang_memory_heapmemoryusage_max{instance=\"zookeeper:8080\"}"
    },
    {
     "expr": "java_lang_memory_heapmemoryusage_committed{instance=\"zookeeper:8080\"}"
    }
   ]
  },
  { "title": "Kafka-Zookeeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "ZooKeeperDisconnectsPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_server_sessionexpirelistener_zookeeperdisconnects_total"
    }
   ]
  },
  {
   "title": "ZooKeeperDisconnectsPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_server_sessionexpirelistener_zookeeperdisconnects_total"
    }
   ]
  },
  {
   "title": "ZooKeeperAuthFailuresPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_sessionexpirelistener_zookeeperauthfailures_total[1m])"
    }
   ]
  },
  {
   "title": "ZooKeeperReadOnlyConnectsPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_sessionexpirelistener_zookeeperreadonlyconnects_total[1m]) "
    }
   ]
  },
  {
   "title": "ZooKeeperSyncConnectsPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_sessionexpirelistener_zookeepersyncconnects_total[1m])"
    }
   ]
  },
  {
   "title": "ZooKeeperSaslAuthenticationsPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_sessionexpirelistener_zookeepersaslauthentications_total[1m])"
    }
   ]
  }
 ]
}